# Generated by Django 4.2.7 on 2025-12-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='items_summary',
            field=models.TextField(blank=True, verbose_name='Состав заказа'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказа'),
        ),
    ]
